version: '3.8'

services:
  php:
    image: php:8.0.3-fpm
    container_name: my_php_container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    ports:
      - "8001:8001"
    environment:
      - APP_ENV=dev
      - APP_DEBUG=true
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - my_network
    command: ["symfony", "server:start", "--port=8001", "--no-tls"]

  db:
    image: mysql:latest
    container_name: my_mysql_container
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: symfony_db
      MYSQL_PASSWORD: ''
    ports:
      - "3307:3306"  # Change the host port to 3307
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
