<?php return array(
    'root' => array(
        'name' => 'symfony/skeleton',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'doctrine/cache' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1ca8f21980e770095a31456042471a57bc4c68fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'reference' => 'd8af7f248c74f195f7347424600fd9e17b57af59',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '3.8.6',
            'version' => '3.8.6.0',
            'reference' => 'b7411825cf7efb7e51f9791dea19d86e43b399a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.3',
            'version' => '1.1.3.0',
            'reference' => 'dfbaa3c2d2e9a9df1118213f3b8b0c597bb99fab',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-bundle' => array(
            'pretty_version' => '2.12.0',
            'version' => '2.12.0.0',
            'reference' => '5418e811a14724068e95e0ba43353b903ada530f',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/doctrine-migrations-bundle' => array(
            'pretty_version' => '3.3.1',
            'version' => '3.3.1.0',
            'reference' => '715b62c31a5894afcb2b2cdbbc6607d7dd0580c0',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../doctrine/doctrine-migrations-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '2.0.1',
            'version' => '2.0.1.0',
            'reference' => 'b680156fa328f1dfd874fd48c7026c41570b9c6e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '2.0.10',
            'version' => '2.0.10.0',
            'reference' => '5817d0659c5b50c9b950feb9af7b9668e2c436bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => 'c6222283fa3f4ac679f8b9ced9a4e23f163e80d0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '31ad66abc0fc9e1a1f2d9bc6a42668d2fbbcd6dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/migrations' => array(
            'pretty_version' => '3.8.0',
            'version' => '3.8.0.0',
            'reference' => '535a70dcbd88b8c6ba945be050977457f4f4c06c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/migrations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/orm' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '722cea6536775206e81744542b36fa7c9a4ea3e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/orm',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/persistence' => array(
            'pretty_version' => '3.3.3',
            'version' => '3.3.3.0',
            'reference' => 'b337726451f5d530df338fc7f68dee8781b49779',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/persistence',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/sql-formatter' => array(
            'pretty_version' => '1.4.0',
            'version' => '1.4.0.0',
            'reference' => 'd1ac84aef745c69ea034929eb6d65a6908b675cc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/sql-formatter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'friendsofsymfony/rest-bundle' => array(
            'pretty_version' => '3.7.1',
            'version' => '3.7.1.0',
            'reference' => 'db7d9a17da2bcae1bb8e2d7ff320ef3915903373',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../friendsofsymfony/rest-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jms/metadata' => array(
            'pretty_version' => '2.8.0',
            'version' => '2.8.0.0',
            'reference' => '7ca240dcac0c655eb15933ee55736ccd2ea0d7a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jms/metadata',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jms/serializer' => array(
            'pretty_version' => '3.30.0',
            'version' => '3.30.0.0',
            'reference' => 'bf1105358123d7c02ee6cad08ea33ab535a09d5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jms/serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jms/serializer-bundle' => array(
            'pretty_version' => '5.4.0',
            'version' => '5.4.0.0',
            'reference' => '6fa2dd0083e00fe21c5da171556d7ecabc14b437',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../jms/serializer-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/clock' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '6f28b826ea01306b07980cb8320ab30b966cd715',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lcobucci/jwt' => array(
            'pretty_version' => '4.3.0',
            'version' => '4.3.0.0',
            'reference' => '4d7de2fe0d51a96418c0d04004986e410e87f6b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../lcobucci/jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'lexik/jwt-authentication-bundle' => array(
            'pretty_version' => 'v2.21.0',
            'version' => '2.21.0.0',
            'reference' => 'd57159da3f572b42ab609630edb6e27d71b37eca',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../lexik/jwt-authentication-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.9.0',
            'version' => '2.9.0.0',
            'reference' => 'f5ac2c0b0a2eefca70b2ce32a5809992227e75a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'myclabs/deep-copy' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '3a6b9a42cd8f8771bd4295d13e1423fa7f3d942c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../myclabs/deep-copy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'namshi/jose' => array(
            'pretty_version' => '7.2.3',
            'version' => '7.2.3.0',
            'reference' => '89a24d7eb3040e285dd5925fcad992378b82bcff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../namshi/jose',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.0.2',
            'version' => '5.0.2.0',
            'reference' => '139676794dc1e9231bf7bcd123cfc0c99182cb13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/manifest' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '54750ef60c58e43759730615a392c31c80e23176',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/manifest',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phar-io/version' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '4f7fd7836c6f332bb2933569e566a0d6c4cbed74',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phar-io/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'php-http/async-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'php-http/client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '*',
            ),
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '1.29.1',
            'version' => '1.29.1.0',
            'reference' => 'fcaefacf2d5c417e928405b71b400d4ce10daaf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '11.0.3',
            'version' => '11.0.3.0',
            'reference' => '7e35a2cbcabac0e6865fd373742ea432a3c34f92',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '99e95c94ad9500daca992354fa09d7b99abe2210',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-invoker' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '5d8d9355a16d8cc5a1305b0a85342cfa420612be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-invoker',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'd38f6cbff1cdb6f40b03c9811421561668cc133e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '7.0.0',
            'version' => '7.0.0.0',
            'reference' => '8a59d9e25720482ee7fcdf296595e08795b84dc5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '11.2.5',
            'version' => '11.2.5.0',
            'reference' => 'be9e3ed32a1287a9bfda15936cc86fef4e4cf591',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'psr/clock' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'e41a24703d4560fd0acb709162f73b8adfc3aa0d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/clock-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'fe5ea303b0887d5caefd3d431c3e61ad47037001',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psr/simple-cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'sebastian/cli-parser' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '00a74d5568694711f0222e54fb281e1d15fdf04a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/cli-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '6634549cb8d702282a04a774e36a7477d2bd9015',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/code-unit-reverse-lookup' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'df80c875d3e459b45c6039e4d9b71d4fbccae25d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/code-unit-reverse-lookup',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => 'bd0f2fa5b9257c69903537b266ccb80fcf940db8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/complexity' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '88a434ad86150e11a606ac4866b09130712671f0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/complexity',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '6.0.1',
            'version' => '6.0.1.0',
            'reference' => 'ab83243ecc233de5655b76f577711de9f842e712',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '7.1.0',
            'version' => '7.1.0.0',
            'reference' => '4eb3a442574d0e9d141aab209cd4aaf25701b09a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '6.1.2',
            'version' => '6.1.2.0',
            'reference' => '507d2333cbc4e6ea248fbda2d45ee1511e03da13',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '7.0.1',
            'version' => '7.0.1.0',
            'reference' => 'c3a307e832f2e69c7ef869e31fc644fde0e7cb3e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/lines-of-code' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '376c5b3f6b43c78fdc049740bca76a7c846706c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/lines-of-code',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-enumerator' => array(
            'pretty_version' => '6.0.0',
            'version' => '6.0.0.0',
            'reference' => 'f75f6c460da0bbd9668f43a3dde0ec0ba7faa678',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-enumerator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/object-reflector' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => 'bb2a6255d30853425fd38f032eb64ced9f7f132d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/object-reflector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '6.0.1',
            'version' => '6.0.1.0',
            'reference' => '2f15508e17af4ea35129bbc32ce28a814d9c7426',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/type' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => 'b8502785eb3523ca0dd4afe9ca62235590020f3f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/type',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '5.0.0',
            'version' => '5.0.0.0',
            'reference' => '13999475d2cb1ab33cb73403ba356a814fdbb001',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/browser-kit' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '62ab90b92066ef6cce5e79365625b4b1432464c8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/browser-kit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/cache' => array(
            'pretty_version' => 'v7.1.2',
            'version' => '7.1.2.0',
            'reference' => 'e933e1d947ffb88efcdd34a2bd51561cab7deaae',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'df6a1a44c890faded49a5fca33c2d5c5fd3c2197',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/cache-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/cache-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/clock' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '7a4840efd17135cbd547e41ec49fb910ed4f8b98',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/clock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/config' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '12e7e52515ce37191b193cf3365903c4f3951e35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '6edb5363ec0c78ad4d48c5128ebf4d083d89d3a9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '4b61b02fe15db48e3687ce1c45ea385d1780fe08',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'a4df9dfe5da2d177af6643610c7bee2cb76a9f5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v2.5.3',
            'version' => '2.5.3.0',
            'reference' => '80d075412b557d41002320b96a096ca65aa2c98d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/doctrine-bridge' => array(
            'pretty_version' => 'v7.1.2',
            'version' => '7.1.2.0',
            'reference' => '9fc4bebf69f00d4ebb12ee904d808b496035e2f6',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/doctrine-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '105b56a0305d219349edeb60a800082eca864e4b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/dotenv' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '55aefa0029adff89ecffdb560820e945c7983f06',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'c9b7cc075b3ab484239855622ca05cb0b99c13ec',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '8d7507f02b06e06815e56bb39aa0128e3806208b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '8f93aec25d41b72493c6ddff14e916177c9efc50',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'b51ef8059159330b74a4d52f68e671033c0fe463',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => 'fbb0ba67688b780efbc886c1a0a0948dcf7205d6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/flex' => array(
            'pretty_version' => 'v2.4.5',
            'version' => '2.4.5.0',
            'reference' => 'b0a405f40614c9f584b489d54f91091817b0e26e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/flex',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/framework-bundle' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'c1d1cb0e508e11639283e1e6f8918eef0fa524bd',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/framework-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-client' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '6e9db0025db565bcf8f1d46ed734b549e51e6045',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-client-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => '20414d96f391677bf80078aa55baece78b82647d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-client-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '3.0',
            ),
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '27de8cc95e11db7a50b027e71caaab9024545947',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'cc4a9bec6e1bdd2405f40277a68a6ed1bb393005',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/maker-bundle' => array(
            'pretty_version' => 'v1.60.0',
            'version' => '1.60.0.0',
            'reference' => 'c305a02a22974670f359d4274c9431e1a191f559',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/maker-bundle',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/password-hasher' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '90ebbe946e5d64a5fad9ac9427e335045cf2bd31',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/password-hasher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/phpunit-bridge' => array(
            'pretty_version' => 'v7.1.2',
            'version' => '7.1.2.0',
            'reference' => '8eb63f1c0e2001f97b3cd9ed550b18765cdeb1c8',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/phpunit-bridge',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/polyfill-ctype' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-iconv' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => '64647a7c30b2283f5d49b874d84a18fc22054b7a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => 'a95281b0be0d9ab48050ebd988b967875cdb9fdb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => 'fd22ab50000ef01661e2a31d850ebaa297f8e03c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => '54b8cd7e6c1643d78d011f3be89f3ef1f9f4c675',
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php72' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php73' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php74' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php80' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php81' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php82' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '*',
            ),
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.30.0',
            'version' => '1.30.0.0',
            'reference' => 'dbdcdf1a4dcc2743591f1079d0c35ab1e2dcbbc9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '8d92dd79149f29e89ee0f480254db595f6a6a2c5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'symfony/property-access' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => 'e4d9b00983612f9c0013ca37c61affdba2dd975a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/property-access',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/property-info' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '1a0357ed93a6ab09482435a7818defaa85cad69b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/property-info',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => '60c31bab5c45af7f13091b87deb708830f3c96c0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/runtime' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => 'b4bfa2fd4cad1fee62f80b3dfe4eb674cc3302a0',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../symfony/runtime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/security-bundle' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'adc34df2fe487a13d4410a237202422294c917b2',
            'type' => 'symfony-bundle',
            'install_path' => __DIR__ . '/../symfony/security-bundle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/security-csrf' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => 'f46ab02b76311087873257071559edcaf6d7ab99',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-csrf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/security-http' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '8e70f39626ada36c5492c3aff9369c85d2840948',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/security-http',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'bd1d9e59a81d8fa4acdcea3f617c581f7475a80f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/skeleton' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/stopwatch' => array(
            'pretty_version' => 'v7.1.1',
            'version' => '7.1.1.0',
            'reference' => '5b75bb1ac2ba1b9d05c47fc4b3046a625377d23d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/stopwatch',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/string' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => '76792dbd99690a5ebef8050d9206c60c59e681d7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v3.5.0',
            'version' => '3.5.0.0',
            'reference' => 'b9d2189887bb6b2e0367a9fc7136c5239ab9b05a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'ee0a4d6a327a963aee094f730da238f7ea18cb01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'c31566e4ca944271cc8d8ac6887cbf31b8c6a172',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v6.4.9',
            'version' => '6.4.9.0',
            'reference' => 'f9a060622e0d93777b7f8687ec4860191e16802e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v6.4.8',
            'version' => '6.4.8.0',
            'reference' => '52903de178d542850f6f341ba92995d3d63e60c9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'theseer/tokenizer' => array(
            'pretty_version' => '1.2.3',
            'version' => '1.2.3.0',
            'reference' => '737eda637ed5e28c3413cb1ebe8bb52cbf1ca7a2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../theseer/tokenizer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'willdurand/jsonp-callback-validator' => array(
            'pretty_version' => 'v2.0.0',
            'version' => '2.0.0.0',
            'reference' => '738c36e91d4d7e0ff0cac145f77057e0fb88526e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/jsonp-callback-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'willdurand/negotiation' => array(
            'pretty_version' => '3.1.0',
            'version' => '3.1.0.0',
            'reference' => '68e9ea0553ef6e2ee8db5c1d98829f111e623ec2',
            'type' => 'library',
            'install_path' => __DIR__ . '/../willdurand/negotiation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
