# controllers:
#     resource: '../src/Controller/'
#     type: attribute

api_login_check:
    path: /api/login_check
    methods: POST

api_product_index:
    path: /api/products
    controller: 'App\Controller\ProductController::index'
    methods: ['GET']

api_product_create:
    path: /api/products
    controller: 'App\Controller\ProductController::create'
    methods: ['POST']

api_product_show:
    path: /api/products/{id}
    controller: 'App\Controller\ProductController::show'
    methods: ['GET']

api_product_update:
    path: /api/products/{id}
    controller: 'App\Controller\ProductController::update'
    methods: ['PUT', 'PATCH']

api_product_delete:
    path: /api/products/{id}
    controller: 'App\Controller\ProductController::delete'
    methods: ['DELETE']